model:
    arch: fcn8s
data:
    dataset: playment
    train_split: train
    val_split: val
    img_rows: 373
    img_cols: 500
    path: /Users/aniketbhushan/Documents/playment-data
training:
    train_iters: 10
    batch_size: 1
    val_interval: 100
    n_workers: 0
    print_interval: 1
    optimizer:
        name: 'sgd'
        lr: 1.0e-10
        weight_decay: 0.0005
        momentum: 0.99
    loss:
        name: 'cross_entropy'
        size_average: False
    lr_schedule:
    resume: fcn8s_playment_best_model.pkl
